- name: Update apt package cache and install curl
  apt:
    name: curl
    state: present
    update_cache: yes
- name: Install Docker via the official shell script
  shell: "curl -fsSL https://get.docker.com | sh"
  args:
    creates: /usr/bin/docker