name: Manual Test App Deployment

on:
  workflow_dispatch:

jobs:
  deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Verify Swarm Manager IP
        run: |
          echo "=== РУЧНОЙ ТЕСТ ПАЙПЛАЙНА ПРИЛОЖЕНИЯ ==="
          echo "Забираем последний сохраненный IP-адрес из настроек репозитория..."
          echo "Текущий IP для деплоя: ${{ vars.SWARM_MANAGER_IP }}"
      - name: Prepare env file
        run: |
          echo "db_password=${{ secrets.DB_PASSWORD }}" >> manifests/.env.uat


#      - name: Copy docker-compose.app.yml to Server
#        uses: appleboy/scp-action@v0.1.7
#        with:
#          host: ${{ vars.SWARM_MANAGER_IP }}
#          username: ubuntu
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          source: "manifests/docker-compose.app.yml, manifests/.env.uat"
#          target: "/home/ubuntu/apps/my-app/"
#          strip_components: 1
#          use_insecure_cipher: true
      - name: Copy files via native SCP
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TARGET_HOST: ${{ vars.SWARM_MANAGER_IP }}
        run: |
          # 1. Записываем ключ во временный файл и выставляем права
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          # 2. Создаем целевую папку на ВМ, используя переменную $TARGET_HOST
          ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@$TARGET_HOST "mkdir -p /home/ubuntu/apps/my-app/"

          # 3. Копируем файлы без интерактивных запросов
          scp -i private_key.pem -o StrictHostKeyChecking=no manifests/docker-compose.app.yml ubuntu@$TARGET_HOST:/home/ubuntu/apps/my-app/
          scp -i private_key.pem -o StrictHostKeyChecking=no manifests/.env.uat ubuntu@$TARGET_HOST:/home/ubuntu/apps/my-app/

          # 4. Удаляем временный файл ключа
          rm -f private_key.pem




      - name: Deploy App to Swarm
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SWARM_MANAGER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/apps/my-app/
            cp .env.uat .env
            if ! docker secret inspect db_password >/dev/null 2>&1; then
              echo "Создаем Docker Secret db_password..."
              export $(grep -v '^#' .env | xargs)
              echo "$db_password" | docker secret create db_password -
            fi
            docker stack deploy -c docker-compose.app.yml my-app

      - name: Simulate Deployment Steps
        run: |
          echo "1. Беру файл docker-compose.app.yml из этого репозитория..."
          echo "2. Симулирую отправку файла на IP: ${{ vars.SWARM_MANAGER_IP }}"
          echo "3. Симулирую команду: ssh user@${{ vars.SWARM_MANAGER_IP }} 'docker stack deploy -c docker-compose.app.yml my-app'"
          echo "=== ТЕСТОВЫЙ РЕЛИЗ ЗАВЕРШЕН ==="
