name: Run Ansible Playbook

on:
  workflow_dispatch:

jobs:
  ansible-execution:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Generating secret files
        run: |
          mkdir -p manifests/secrets
          echo "${{ secrets.DB_PASSWORD }}" > manifests/secrets/db_password.txt
          echo "${{ secrets.DB_ROOT_PASSWORD }}" > manifests/secrets/db_root_password.txt
          echo "${{ secrets.FLYWAY_PASSWORD }}" > manifests/secrets/flyway_password.txt

      - name: Run Ansible Playbook
        run: |
          echo "Запуск Ansible плейбука..."
          ansible-playbook -i nodes.ini infra-cluster-setup.yml   
