name: Run Ansible Playbook

on:
  workflow_dispatch:

jobs:
  ansible-execution:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Run Ansible Playbook
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
          FLYWAY_PASSWORD: ${{ secrets.FLYWAY_PASSWORD }}
        run: |
          echo "Запуск Ansible плейбука..."
          ansible-playbook -i nodes.ini infra-cluster-setup.yml   
